import { defineTheme } from "../components/ui/theme";

/** Generated by Balsa UI. Edit this definition in your application. */
export const karmancosTheme = defineTheme({
  "id": "karmancos",
  "name": "Karmancos",
  "extends": "glassmorphism"
});
